### ISSUE TITLE
Sometimes segments with "no_speech_prob" larger than "speech threshold" and "avg_logprob" lower than "logprob_threshold" still appear

### ISSUE THREAD

**Issue by ItakeLs** [linto-ai/whisper-timestamped#26]
Sorry to do this again, I'm not sure if this is by design, but sometimes segments with both ```no_speech_prob``` larger than ```speech threshold``` and ```avg_logprob``` lower than ```logprob_threshold``` still appear, which often result is hallucinated segments. This happened in the first segment not sure if it happens in other areas,

In this specific case this was with ```beam_size=5```, ```condition_on_previous_text=False```, ```best_of=5``` and ```temperature=(0.0, 0.2, 0.4, 0.6, 0.8, 1.0)```.

**Comment by Jeronymous** [comment]
This is certainly not by design.

I double checked that `no_speech_threshold` and `logprob_threshold` are correctly passed to `whisper.transcribe()`.
And with the options that you give (beam search...), the transcription is first done by whisper and segments should just be identical in the end (except from start and end timestamp).

So I don't understand what can happen.
Can you please double check, and give what python call you make and an extract of the output that you find suspicious?
(Also you can test what gives whisper alone on this)

**Comment by ItakeLs** [comment]
Yes, you are right, the issue was on my end, after thorough checking, it is working as intended.
