### ISSUE TITLE
Issue of duplicate word lines

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [linto-ai/whisper-timestamped#28]
The script works just fine as I try to transcribe an audio file in Arabic language but when It reaches 6min out of 8, It starts duplicating one line even though the timing is correct but the lexical is not.

![image](https://user-images.githubusercontent.com/78225592/216867848-5d748a20-feb1-4404-9cc2-ee0ca38c7a7e.png)

**Comment by Jeronymous** [comment]
I think it is the same as issue #16 

Try if you have better results with `--accurate` option in the CLI (or `beam_size=5, best_of=5, temperature=(0.0, 0.2, 0.4, 0.6, 0.8, 1.0)` if you call the `transcribe` function).

If not, it's a problem of whisper itself (which you can check by using `whisper` instead of `whisper_timestamped`)

**Comment by Jeronymous** [comment]
Closing for lack of feedback. Feel free to re-open

**Comment by MohammedMehdiTBER** [comment]
> Closing for lack of feedback. Feel free to re-open

It worked well now that I used **`--accurate`**
