### ISSUE TITLE
[Bug] Unable to use multiple output formats directly (without "all")

### ISSUE THREAD

**Issue by misutoneko** [linto-ai/whisper-timestamped#56]
Hi,

I was trying to define multiple output formats directly with format names (without using the "all" option).
I couldn't figure out how to do it, and it eventually dawned to me that this might be a parsing bug. I think the problem is that if you give it a string like "json,srt", that will not match any of the pre-defined strings in choices[].

The diff below fixes the issue, but the commas were lost, so need to use something like "-f json srt" (without the quotes).

[output_format_diff.gz](https://github.com/linto-ai/whisper-timestamped/files/10930820/output_format_diff.gz)

**Comment by Jeronymous** [comment]
Indeed the `output_format = output_format.split(",")` in the code is misleading.
Specifying several formats is not implemented (and not documented).
I just did the same as what whisper does, for the sake of simplicity, and gave up my first idea to be able to specify several formats.

For now, I am not super comfortable with making --output_format a "`nargs="+"`" option, as we are already accepting several audio as input arguments, and it could be a mess to parse the arguments.
Have you tested your solution with several audio and several specific output formats?

The thing with "," instead of spaces can be implemented. Just "choices" should not be used (but rather a specific option parser instead).

**Comment by misutoneko** [comment]
Thanks for clarification. I haven't tested this extensively, but it "works for me", as they say :D
From the user pov it would be more clear to be able to use commas.
